application:
  data-generator:
    first-name:
      - Super
      - Retarded
      - Great
      - Sexy
      - Vegan
      - Brave
      - Shy
      - Cool
      - Poor
      - Rich
      - Fast
      - Gummy
      - Yummy
      - Masked
      - Unusual
      - American
      - Bisexual
      - MLG
      - Mlg
      - lil
      - Lil
    last-name:
      - Coder
      - Vegan
      - Man
      - Hacker
      - Horse
      - Bear
      - Goat
      - Goblin
      - Learner
      - Killer
      - Woman
      - Programmer
      - Spy
      - Stalker
      - Spooderman
      - Carrot
      - Goat
      - Quickscoper
      - Quickscoper